#!/bin/bash

START_DIR="$(pwd)"
cd /workspaces/lookout

cd server
echo "Installing node in /server..."
npm install

cd ../frontend
echo "Installing node in /frontend..."
npm install

cd ../server
npm run dev &

cd ../frontend
npm run dev

cd $START_DIR